### ISSUE TITLE
Remember breakpoints per project

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-atom-ide-debugger#1]
https://community.platformio.org/t/platformio-debugging/1704/9?u=ivankravets

**Comment by ivankravets** [comment]
@sstaub Please update pio-atom-debugger package to 1.2.0 and re-test. Does it work for you?

**Comment by sstaub** [comment]
I tested with stm32nucleo L432KC and the breakpoint remembering works.

**Comment by ivankravets** [comment]
@sstaub Thanks a lot! ;)
