### ISSUE TITLE
Uncaught TypeError: cmd(...).catch is not a function

### ISSUE THREAD

**Issue by madhephaestus** [platformio/platformio-atom-ide-debugger#7]
[Enter steps to reproduce:]

1. Load a sample project for the Nucleo-f746zg
2. run debug mode
3. run program button

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [platformio-ide-debugger](https://github.com/platformio/platformio-atom-ide-debugger) package 1.2.2

### Stack Trace

Uncaught TypeError: cmd(...).catch is not a function

```
At /home/hephaestus/.atom/packages/platformio-ide-debugger/lib/main.coffee:79

TypeError: cmd(...).catch is not a function
    at Object.cmdWrap (/packages/platformio-ide-debugger/lib/main.coffee:78:9)
    at /packages/platformio-ide-debugger/lib/main.coffee:39:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:1)
    at HTMLButtonElement.module.exports.GdbToolbarView.do (/packages/platformio-ide-debugger/lib/gdb-toolbar-view.coffee:35:23)
```

### Commands

```
     -1:23.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:09.2.0 platformio-ide:target:debug (atom-pane.pane.active)
     -1:09.2.0 platformio-ide:target:debug-/home/hephaestus/git/AS5050 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:12.7.0 platformio-ide-debugger:continue (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.7 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-ide 2.0.0-beta.4 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
What does mean `3. run program button` step?

**Comment by madhephaestus** [comment]
3 is hitting the "play button" in the debug interface. 
There is also an error
Error: libusb_open() failed with LIBUSB_ERROR_ACCESS

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type `pio debug --interface=gdb -x .pioinit`. Do you see any errors?

**Comment by madhephaestus** [comment]
pio debug --interface=gdb -x .pioinit
PlatformIO Plus (https://pioplus.com) v0.8.14
[Mon Jun  5 18:41:34 2017] Processing nucleo_f746zg (platform: ststm32; bo
ard: nucleo_f746zg; framework: mbed)
--------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Collected 8 compatible libraries
Looking for dependencies...
Project does not have dependencies
Calculating size .pioenvs/nucleo_f746zg/firmware.elf
text       data     bss     dec     hex filename
43800      2240    1852   47892    bb14 .pioenvs/nucleo_f746zg/firmware.el
f
====================== [SUCCESS] Took 2.15 seconds ======================
GNU ARM Eclipse 64-bits Open On-Chip Debugger 0.10.0-00114-g8419536 (2017-

04-18-22:28)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The resu
lts might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Error: libusb_open() failed with LIBUSB_ERROR_ACCESS
Error: open failed
in procedure 'init'
in procedure 'ocd_bouncer'

.pioinit:1: Error in sourced command file:
Remote communication error.  Target disconnected.: Connection reset by pee
r.
(gdb)

**Comment by ivankravets** [comment]
Have you installed `udev` rules?

* https://github.com/platformio/platformio-core/blob/develop/scripts/98-openocd-udev.rules

**Comment by ivankravets** [comment]
Also, see https://www.google.com.ua/search?client=safari&rls=en&q=openocd+libusb_open()+failed+with+LIBUSB_ERROR_ACCESS&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=9N81WaeZBabi8AePhoO4AQ

**Comment by ivankravets** [comment]
`sudo usermod -aG plugdev $USER`

**Comment by madhephaestus** [comment]
Excellent! yes that fixed it. I had come across https://github.com/texane/stlink/blob/master/etc/udev/rules.d/49-stlinkv2-1.rules

**Comment by ivankravets** [comment]
Thanks! We will update our documentation and add a few notes about Linux.
